version: '3'
services:
  app:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      "db":
        condition: service_healthy
    environment:
      DB_USER: admin
      DB_PASSWORD: Cod79022023b!
      DB_HOST: records-db-1
      DB_PORT: 3306
      DB_NAME: db1_mysql

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Cod79022023b!
      MYSQL_DATABASE: db1_mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: Cod79022023b!
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  db_data: