version: '1.0'
services:
  web:
    build: .
    command: sh -c "uvicorn app:app --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    environment:
      - DB_HOST="localhost"
      - DB_PORT= 3306
      - DB_USER="admin"
      - DB_PASSWORD="Cod79022023b!"
      - DB_NAME="financedb"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: DB_NAME
      MYSQL_USER: DB_USER
      MYSQL_PASSWORD: DB_PASSWORD
    ports:
      - "3306:3306"